### ISSUE TITLE
/explore:  time axis legend and data out of sync when Download Time Format squeezes

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#21]
![image](https://user-images.githubusercontent.com/324851/101026751-4a454000-3545-11eb-8285-5650858cff85.png)

To repro:
Show channel A
click download icon to reveal Donwload Time Format
Show channel B
Channel B is now out of sync with the time axis.  You can remove channel A.

**Comment by dognotdog** [comment]
Good catch, should be fixed in e63eff7

**Comment by rsargent** [comment]
Partially fixed.  But in cases where the channel name is too long, it breaks?

![image](https://user-images.githubusercontent.com/324851/101084547-22250380-357c-11eb-80c7-41778cff7342.png)

**Comment by dognotdog** [comment]
@rsargent 10b00b8 should fix the issue above, which was caused by the plot labels preventing further shrinking of the plot area. they are now cut off.

**Comment by rsargent** [comment]
Confirmed fix, thanks!
